dist: xenial
sudo: true

install:
  - ./gradlew --console=plain prepareDockerImage
script:
  - ./gradlew --console=plain buildDockerImage
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
