version: "3.7"

secrets:
  # example host key for testing
  ssh_host_rsa_key:
    file: ./secrets/ssh_host_rsa_key

services:
  uploader:
    image: lovelysystems/scp2s3:dev
    hostname: localhost
    environment:
      # The authorized keys allowed to upload content
      AUTHORIZED_KEYS: |
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDjLENUYimjTZLNt97i9mcYmEmKHm1jUpBb+niqhxjBUVG03m9KkogNWxn+56Hq2d6vvt5qn2Jpj5AdkOJUzBsMIRFT+4mW7Elyew8sw3Dax/tA7xvu4ptnFvxnMg8GBxWlj5HCfgeE4xgiLPGF1xE5SByTHzFDGwGzX5oWy6EZw8D4EagveYMqHvIoLxZSVyrLnV6349QwJkvwTO1a8ZvFZkfw4dfIzhGi7C7y2eHO7LwXq7MhGQSlV/YQcrJegWXB6grWDba/a5FsQKr7ZveRZdwiewerTC/G11fHwYg7NzIGnR252h2WhvCBt1BcqS0YK9KONGdBgHAWKhGShBU3 key1
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDrW2mzKjKACkyTPKmApHKBah9/8+V240K8uw7St7Y927Hkx3EJA6gep8IEw5xDuQ0mUo0tgazJcWmLmuh8dftBqgAgYqk4K+sLMrP98RkIjljsRwm9U7WtnB+ByWRq6+w8xIPd/0nD32XRNyDDCPV40ccaNETrbbbWX0Md36Riy9BT0v2cTlE7kyE21yJrXO9T199v64Urry5p9ReCbs99lAoerduukwRVQM+jcyEQpsYrJxFr985TSHT2eODOwZnbSbdbVoWLdOY41u0+4q2yQWvRxI/BbMhKGMGaq9/D7FACuNMi8mM/cx56LHGH408NaBmbpwBoYHii6DmtGHPV key2
      # aws credentials in this example taken fron the host environment
      AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
      AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
      # pattern to convert the input filename to an output host absolute path on s3 including the bucket
      # e.g: x.tgz -> /some-bucket/x.tgz
      # if the output of: sed -nE $PATH_PATTERN  returns a non empty string it is used as target path
      # and the file will be uploaded and deleted after the upload
      # if no output is generated the file will not be uploaded but kept locally
      PATH_PATTERN: 's#^(.*)$$#/some-bucket/\1#p'
    secrets:
      - ssh_host_rsa_key
    ports:
      - "10044:22"
      - "9001:9001"